In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
df = df.drop(['Id'], axis= 1)
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
y = df.Species
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [6]:
x = df.drop(['Species'], axis=1)
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size = 0.3)

In [8]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

### LogisticRegression

In [10]:
model_lr = LogisticRegression()

In [11]:
model_lr.fit(x_train, y_train)

LogisticRegression()

In [12]:
model_lr.score(x_test, y_test)

0.9555555555555556

### DecisionTreeClassifier

In [13]:
model_dt = DecisionTreeClassifier()

In [14]:
model_dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [15]:
model_dt.score(x_test , y_test)

0.8888888888888888

### RandomForestClassifier

In [16]:
model_rfc = RandomForestClassifier()

In [17]:
model_rfc.fit(x_train, y_train)

RandomForestClassifier()

In [18]:
model_rfc.score(x_test , y_test)

1.0

### SVM

In [19]:
model_svc = SVC()

In [20]:
model_svc.fit(x_train, y_train)

SVC()

In [21]:
model_svc.score(x_test , y_test)

0.9333333333333333

In [22]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [23]:
Logistic_Regression = cross_val_score(LogisticRegression(), x, y, cv = 3)

In [24]:
Decision_Tree = cross_val_score(DecisionTreeClassifier(), x, y, cv = 3)

In [25]:
Random_Forest = cross_val_score(RandomForestClassifier(), x, y, cv = 3)

In [26]:
svm = cross_val_score(SVC(), x, y, cv = 3)

In [27]:
print(Logistic_Regression)
print(Decision_Tree)
print(Random_Forest)
print(svm)

[0.98 0.96 0.98]
[0.98 0.92 0.96]
[0.98 0.94 0.96]
[0.96 0.98 0.94]
