In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('spam_ham_dataset.csv')
df

Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
5166          0  
5167          0  
5168          0  
5169          0  
5170          1  

[5171 rows x 4 columns]

In [3]:
df = df.drop(['Unnamed: 0'], axis=1)
df

label                                               text  label_num
0      ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1      ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2      ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3     spam  Subject: photoshop , windows , office . cheap ...          1
4      ham  Subject: re : indian springs\r\nthis deal is t...          0
...    ...                                                ...        ...
5166   ham  Subject: put the 10 on the ft\r\nthe transport...          0
5167   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...          0
5168   ham  Subject: calpine daily gas nomination\r\n>\r\n...          0
5169   ham  Subject: industrial worksheets for august 2000...          0
5170  spam  Subject: important online banking alert\r\ndea...          1

[5171 rows x 3 columns]

In [7]:
df2 = df.copy()

In [8]:
df2

label                                               text  label_num
0      ham  Subject: enron methanol ; meter # : 988291\r\n...          0
1      ham  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2      ham  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3     spam  Subject: photoshop , windows , office . cheap ...          1
4      ham  Subject: re : indian springs\r\nthis deal is t...          0
...    ...                                                ...        ...
5166   ham  Subject: put the 10 on the ft\r\nthe transport...          0
5167   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...          0
5168   ham  Subject: calpine daily gas nomination\r\n>\r\n...          0
5169   ham  Subject: industrial worksheets for august 2000...          0
5170  spam  Subject: important online banking alert\r\ndea...          1

[5171 rows x 3 columns]

In [9]:
df2 = df2.drop(['label_num'], axis = 1)
df2

label                                               text
0      ham  Subject: enron methanol ; meter # : 988291\r\n...
1      ham  Subject: hpl nom for january 9 , 2001\r\n( see...
2      ham  Subject: neon retreat\r\nho ho ho , we ' re ar...
3     spam  Subject: photoshop , windows , office . cheap ...
4      ham  Subject: re : indian springs\r\nthis deal is t...
...    ...                                                ...
5166   ham  Subject: put the 10 on the ft\r\nthe transport...
5167   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...
5168   ham  Subject: calpine daily gas nomination\r\n>\r\n...
5169   ham  Subject: industrial worksheets for august 2000...
5170  spam  Subject: important online banking alert\r\ndea...

[5171 rows x 2 columns]

In [10]:
df2.groupby('label').describe()

text                                                               
      count unique                                                top freq
label                                                                     
ham    3672   3531  Subject: calpine daily gas nomination\r\n>\r\n...   20
spam   1499   1462                                      Subject: \r\n   16

In [13]:
df2['spam'] = df2['label'].apply(lambda x: 1 if x == 'spam' else 0)

In [14]:
df2

label                                               text  spam
0      ham  Subject: enron methanol ; meter # : 988291\r\n...     0
1      ham  Subject: hpl nom for january 9 , 2001\r\n( see...     0
2      ham  Subject: neon retreat\r\nho ho ho , we ' re ar...     0
3     spam  Subject: photoshop , windows , office . cheap ...     1
4      ham  Subject: re : indian springs\r\nthis deal is t...     0
...    ...                                                ...   ...
5166   ham  Subject: put the 10 on the ft\r\nthe transport...     0
5167   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...     0
5168   ham  Subject: calpine daily gas nomination\r\n>\r\n...     0
5169   ham  Subject: industrial worksheets for august 2000...     0
5170  spam  Subject: important online banking alert\r\ndea...     1

[5171 rows x 3 columns]

In [15]:
from sklearn.model_selection import train_test_split


In [16]:
y = df2['spam']

In [17]:
x = df2['text']

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
v = CountVectorizer()

In [22]:
v

CountVectorizer()

In [23]:
x_train_count = v.fit_transform(x_train.values)

In [24]:
x_train_count

<4136x44996 sparse matrix of type '<class 'numpy.int64'>'
	with 362788 stored elements in Compressed Sparse Row format>

In [25]:
x_train_count.toarray()

array([[0, 3, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
x_train_count.toarray()[:3]

array([[0, 3, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
from sklearn.naive_bayes import MultinomialNB

In [28]:
model = MultinomialNB()

In [29]:
model.fit(x_train_count, y_train)

MultinomialNB()

In [31]:
x_test_count = v.transform(x_test)

In [32]:
model.score(x_test_count, y_test)

0.978743961352657

In [37]:
emails = ["Sale Ends Today! Don't Miss on Biggest Savings on Summer Essentials!", "Customer Experience - #MiWithYou - Xiaomi Service+ Edition",
"You’re invited to upskill faster with Google Cloud", "Hey Athul Can we get together to watch IPL"]

In [38]:
emails_count = v.transform(emails)

In [39]:
model.predict(emails_count)

array([0, 1, 1, 0], dtype=int64)

In [40]:
from sklearn.pipeline import Pipeline