In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x = df.drop(['Outcome'], axis = 1)
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [6]:
y = df['Outcome']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x , y , test_size = 0.3, random_state =1)

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
model_tree = DecisionTreeClassifier()

In [10]:
model_tree.fit(x_train, y_train)
model_tree.score(x_test, y_test)

0.7012987012987013

In [11]:
model_tree.score(x_train, y_train)

1.0

In [12]:
from sklearn.ensemble import AdaBoostClassifier

In [13]:
model_ada = AdaBoostClassifier(n_estimators=50 , learning_rate=1)

In [14]:
model_ada.fit(x_train,y_train)

AdaBoostClassifier(learning_rate=1)

In [15]:
model_ada.score(x_test, y_test)

0.7835497835497836

In [16]:
y_predict = model_ada.predict(x_test)
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score

In [18]:
accuracy_score(y_test, y_predict)

0.7835497835497836

In [19]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix

In [20]:
performance = confusion_matrix(y_test, y_predict)
performance

array([[131,  15],
       [ 35,  50]], dtype=int64)

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
model_rst = AdaBoostClassifier(base_estimator=RandomForestClassifier(n_estimators=100),
 n_estimators=50, learning_rate=1)

In [23]:
model_rst.fit(x_train,y_train)

AdaBoostClassifier(base_estimator=RandomForestClassifier(), learning_rate=1)

In [24]:
model_rst.score(x_test,y_test)

0.7878787878787878

In [25]:
y_predict = model_rst.predict(x_test)

In [26]:
accuracy_score(y_test, y_predict)

0.7878787878787878

In [27]:
confusion_matrix(y_test, y_predict)

array([[131,  15],
       [ 34,  51]], dtype=int64)

In [28]:
from sklearn.svm import SVC

In [29]:
model_svm = AdaBoostClassifier(base_estimator=SVC(gamma='auto', kernel='linear'),
 n_estimators=50, learning_rate=1, algorithm='SAMME')

In [30]:
model_svm.fit(x_train,y_train)

AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=SVC(gamma='auto', kernel='linear'),
                   learning_rate=1)

In [31]:
model_svm.score(x_test,y_test)

0.7835497835497836